SDK_DEMO_PATH ?= .
PLUMBL_SDK_BASE = $(SDK_DEMO_PATH)/../../
export PLUMBL_SDK_BASE

BL_TYPE?=uf2
DEBUG?=n
CHIP?=xxx
CHIP_FAMILY?=xxx
BOARD?=xxx
USBIP?=xxx
RTT_VIEWER?=y
TOOLCHAIN_PREFIX ?= arm-none-eabi-

include $(PLUMBL_SDK_BASE)/project.build