SDK_DEMO_PATH ?= .
PLUMBL_SDK_BASE = $(SDK_DEMO_PATH)/../..
export PLUMBL_SDK_BASE

BL_TYPE?=uf2
DEBUG?=n
CHIP?=ch58x
CHIP_FAMILY?=ch58x
BOARD?=ch582_plum
USBIP?=ch32
USB_DCD?=usb_ch58x_dc_usbfs.c
TOOLCHAIN_PREFIX ?= riscv-none-embed-

include $(PLUMBL_SDK_BASE)/project.build