SDK_DEMO_PATH ?= .
PLUMBL_SDK_BASE = $(SDK_DEMO_PATH)/../..
export PLUMBL_SDK_BASE

BL_TYPE?=uf2
USE_MCU_BOOT?=n
DEBUG?=n
CHIP?=ch32v307
CHIP_FAMILY?=ch32v30x
BOARD?=ch32v30x_plum
USBIP?=ch32
USB_DCD?=usb_dc_usbhs.c
TOOLCHAIN_PREFIX ?= riscv-none-embed-

include $(PLUMBL_SDK_BASE)/project.build