SDK_DEMO_PATH ?= .
PLUMBL_SDK_BASE = $(SDK_DEMO_PATH)/../..
export PLUMBL_SDK_BASE

BL_TYPE?=uf2
DEBUG?=n
CHIP?=stm32l433
CHIP_FAMILY?=stm32l4xx
BOARD?=stm32l433rct6_plum
USBIP?=fsdev
RTT_VIEWER?=y
TOOLCHAIN_PREFIX ?= arm-none-eabi-

include $(PLUMBL_SDK_BASE)/project.build